### ISSUE TITLE
Bug: cdc iterator doesn't seem to capture file deletion.

### ISSUE THREAD

**Issue by alarbada** [ConduitIO/conduit-connector-s3#624]
### Bug description

As title says, I'm tweaking in s3, but when I delete the file in s3 I don't see the change reflected.

I see that the file connector has [some limitations](https://github.com/ConduitIO/conduit-connector-file/tree/main?tab=readme-ov-file#limitations) when writing files, but I don't see why a delete record wouldn't be written (the contents of the record, not the action that the record is supposed to do). Specifically, [here](https://github.com/ConduitIO/conduit-connector-file/blob/5befcfa603e9335d90f8ad65594c0ae4ba33ed23/destination.go#L72-L80) all records are written as is.

### Steps to reproduce

1. Upload a test file in s3, in any bucket.
2. Start conduit with a s3 as source and file as destination as a pipeline. Like this one:

```yaml
version: "2.2"
pipelines:
  - id: example-pipeline
    status: running
    name: "s3-to-file"
    connectors:
      - id: example
        type: source
        plugin: s3
        settings:
          aws.accessKeyId: ...
          aws.secretAccessKey: ....
          aws.region: ...
          aws.bucket: ...

      - id: file
        type: destination
        plugin: "file"
        settings:
          path: ./destination.txt
          sdk.record.format: template
          sdk.record.format.options: '{{ printf "%s" .Operation }}'
```

3. `$ tail -f destination.txt`
4. Delete the s3 object. We should see a `delete` in the file, but we don't.

### Version

(latest conduit & latest versions of mentioned connectors)
